import React, { PropsWithChildren } from "react";
import Head from "next/head";
import { darkTheme } from "@/stitches.config";
import { Flex } from "@/components/primitives/Flex";
import { Block } from "@/components/primitives/Block";
import { Text } from "@/components/primitives/Text";
import { FaceIcon, ImageIcon, SunIcon } from "@radix-ui/react-icons";
import { Camera } from "react-feather";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainContainer>
        <Block className={darkTheme}>
          <Text size={1} variant="primary">
            Text 1
            <FaceIcon />
          </Text>
        </Block>
        <Block>
          <Text size={2} variant="primary">
            Text 2
            <SunIcon />
          </Text>
        </Block>
        <Block>
          <Text variant="red" gradient={true} size={3}>
            Text 3
            <ImageIcon />
          </Text>
        </Block>
        <Camera size={50} color="blue" strokeWidth={0.5} />
      </MainContainer>
    </>
  );
}

const MainContainer: React.FC<PropsWithChildren> = (props) => (
  <Flex direction="column" align="center" justify="center" gap={4} {...props} />
);
